=== infoculture/opengovdataru/schema.opengovdata.ru/html/0.1/opendata.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.1.0.1135 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified"
  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="opendata">
    <xs:annotation>
      <xs:documentation>Корневой тэг спецификации открытых данных</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" name="source">
          <xs:annotation>
            <xs:documentation>Описание источника данных</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="1" name="name" type="xs:string">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Наименование источника информации</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="description" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Подробное описание источника данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="org">
                <xs:annotation>
                  <xs:documentation>Информация об организации ведующей данный массив данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="1" name="name" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Наименование ответственной организации</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="description" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Описание организации
</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="website" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Веб-сайт организации ведущей данный источник информации</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="address" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Юридический адрес местонахождения организации ведущей данный источник данных</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="language" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Язык на котором представлена информация в источнике данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="location" type="xs:string">
                <xs:annotation>
                  <xs:documentation>веб-ссылка на источник данных если он есть. Может ссылаться на http и ftp ресурсы</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required">
              <xs:annotation>
                <xs:documentation xml:lang="ru">Уникальный идентификатор источника информации</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="datainfo">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="datatype">
                <xs:annotation>
                  <xs:documentation>Информация о типе массива данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="is_updatable" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Флаг отмечаемый в True если источник данных не является статическим и пополняется новой информацией и в False если он является статическим</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="created" type="xs:dateTime">
                <xs:annotation>
                  <xs:documentation>Дата создания массива данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="updated" type="xs:dateTime">
                <xs:annotation>
                  <xs:documentation>Дата последнего обновления источника данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" maxOccurs="1" name="preparedBy">
                <xs:annotation>
                  <xs:documentation>Информация о человеке подготовившем материалы для данного источника информации</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="1" name="author" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>ФИО автора </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="authorWebsite" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Сайт автора (если есть)</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="specs">
          <xs:annotation>
            <xs:documentation>Спецификации и описание структуры данных из источника</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="specref">
                <xs:annotation>
                  <xs:documentation>Сслылка на описание спецификации во внешнем файле</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Идентификатор спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="url" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Веб-ссылка на документ спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="isSpecial" type="xs:boolean" use="required">
                    <xs:annotation>
                      <xs:documentation>Флаг того представлена ли спецификация в специальном формате. Например, в виде простого описания</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="tablespec">
                <xs:annotation>
                  <xs:documentation>Спецификация табличных данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="cols">
                      <xs:annotation>
                        <xs:documentation>Перечень спецификаций столбцов</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="colspec">
                            <xs:annotation>
                              <xs:documentation>Спецификация столбца данных</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="name" type="xs:string">
                                  <xs:annotation>
                                    <xs:documentation>Название столбца</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element minOccurs="0" name="description" type="xs:string">
                                  <xs:annotation>
                                    <xs:documentation>Описание столбца</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="num" type="xs:unsignedByte" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Номер столбца от начала ряда в таблице</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="key" type="xs:string" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Уникальный ключ, идентификатор данного столбца</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="unique" type="xs:boolean" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Если установлен в True, то данные в столбце являеются уникальными в рамках всей таблицы</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="type" type="xs:string" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Тип данных в столбце. Может принимать значения:
1. string - строка
2. integer - число
3. url - ссылка на внешний ресурс
4. date - дата в формате ISO:  YYYY-MM-DD
5. datetime - дата и время в формате ISO: YYYY-MM-DD HH:MM:SS</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Идентификатор спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="data">
          <xs:annotation>
            <xs:documentation>Открытые данные</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="current">
                <xs:annotation>
                  <xs:documentation>Текущие данные</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="table">
                      <xs:annotation>
                        <xs:documentation>Таблица с  данными</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="row">
                            <xs:annotation>
                              <xs:documentation>Ряд - запись в таблице</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" maxOccurs="unbounded" name="col">
                                  <xs:annotation>
                                    <xs:documentation>Столбец в записи таблицы</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="num" type="xs:unsignedByte"
                                          use="required">
                                          <xs:annotation>
                                            <xs:documentation>Номер столбца в записи - уникален в пределах одной записи</xs:documentation>
                                          </xs:annotation>
                                        </xs:attribute>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="specid" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Идентификатор спецификации</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="type" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Тип таблицы</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="date_updated" type="xs:dateTime" use="required">
                          <xs:annotation>
                            <xs:documentation>Дата последнего обновления</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="tableref">
                      <xs:annotation>
                        <xs:documentation>Ссылка на внешний файл таблицы с данными</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Тип таблицы - может принимать одно из значений:
1. full - таблица со всеми данными
2. initial - начальные данные на которые далее накладываются все обновления. Должен обладать updateid = 0
2. update - обновления к начальным данным которые обладают updateid инкрементально возрастающим от обновления к обновлению</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="specid" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Идентификатор спецификации данных</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="format" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Формат данных в таблице. Может быть одним из значений:
1. CSV
2. TSV
3. DBF
4. XML</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="url" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Ссылка на внешний файл с данными в указанном формате</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="hash_sha512" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Хэш внешнего файла рассчитанный по алгоритму SHA-512</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="date_updated" type="xs:dateTime" use="required">
                          <xs:annotation>
                            <xs:documentation>Дата последнего обновления</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="updateid" type="xs:unsignedLong" use="optional">
                          <xs:annotation>
                            <xs:documentation>Идентификатор обновления если тип таблицы update, то это инкрементальное число начинающееся от 1.
Если тип таблицы initial, то updateid всегда равен 0
Для таблиц типа full - не используется</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/zakupki.gov.ru/Nomenklatura/opendata.xml
<?xml version='1.0' encoding='utf8'?>
<opendata ns0:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd" xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance">
	<source id="zakupki_gov_ru_Nomenklatura">
		<name>Структурированная номенклатура продукции для государственных и муниципальных нужд</name>
		<description>Структурированная номенклатура продукции для государственных и муниципальных нужд.</description>
		<org>
			<name>Минэкономразвития</name>
			<description>Министерство Экономического развития Российской Федерации</description>
			<website>http://www.economy.gov.ru/</website>
			<address>125993, ГСП-3, Москва, А-47, 1-я Тверская-Ямская ул., д.1,3</address>
		</org>
		<language>ru-RU</language>
		<location>http://www.zakupki.gov.ru/Default.aspx?link=21</location>
	</source>
	<datainfo>
		<datatype is_updatable="True" />
		<created>2009-08-30T12:28:37Z</created>
		<updated>2009-08-30T12:28:37Z</updated>
		<preparedBy>
			<author>Ivan Begtin</author>
			<authorWebsite>http://ivan.begtin.name</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="zakupki_gov_ru_Nomenklatura_table">
			<cols>
				<colspec key="code" num="1" type="string" unique="true">
					<name>Код</name>
					<description>Код структурированной номенклатуры</description>
				</colspec>
				<colspec key="measure" num="2" type="string">
					<name>Единицы измерений</name>
					<description>Единицы измерний по ОКЕИ</description>
				</colspec>
				<colspec key="name" num="3" type="string">
					<name>Наименование</name>
					<description>Наименование записи</description>
				</colspec>
				<colspec key="level" num="4" type="integer">
					<name>Уровень</name>
					<description>Уровень кода в иерархии от 1 до 7.</description>
				</colspec>
				<colspec key="parent" num="5" type="string">
					<name>Код вышестоящей записи</name>
					<description>Код вышестоящей записи</description>
				</colspec>
				<colspec key="type" num="6" type="string">
					<name>Признак типа записи</name>
					<description>G - для товаров, R - для работ и S - для услуг</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
		<tableref date_updated="2009-08-31T04:37:54.273239" format="CSV" hash_sha512="3aa466ec66b480855386e457149285ef74a8387ee2f93e4e12c915dc4d7b996ffa2a349102ec4110a010de7d838719a6c743287559282856555029ced10e6e67" specid="zakupki_gov_ru_Nomenklatura_table" type="full" url="http://export.opengovdata.ru/data/0.1/zakupki.gov.ru/Nomenklatura/zakupki_gov_ru_Nomenklatura.csv" /><tableref date_updated="2009-08-31T04:37:54.897927" format="TSV" hash_sha512="45fc80d906442c5812c70c4133fa57e9fd583ce517061620524165801292993ab004526abcdf4b980d125fd6b77b75bb7bfd057532d36c1fa26780018dffed39" specid="zakupki_gov_ru_Nomenklatura_table" type="full" url="http://export.opengovdata.ru/data/0.1/zakupki.gov.ru/Nomenklatura/zakupki_gov_ru_Nomenklatura.tsv" /><tableref date_updated="2009-08-31T04:38:30.121029" format="openDataXML" hash_sha512="26137855adc86117ac9c72e495ae986d47fee097124bcc0040c64c0ab09b41135cd1e990be5cd8d4c9196e6f27362f4a25e697e380add541f28c445ffa8a869e" specid="zakupki_gov_ru_Nomenklatura_table" type="full" url="http://export.opengovdata.ru/data/0.1/zakupki.gov.ru/Nomenklatura/zakupki_gov_ru_Nomenklatura.xml" /></current>
	</data>
</opendata>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/roskazna.ru/TerrDepartments/opendata.xml
<?xml version='1.0' encoding='utf8'?>
<opendata ns0:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd" xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance">
	<source id="roskazna_ru_TerrDepartments">
		<name>Территориальные органы Федерального Казначейства</name>
		<description>АДРЕСНО - ТЕЛЕФОННЫЙ СПРАВОЧНИК УПРАВЛЕНИЙ ФЕДЕРАЛЬНОГО КАЗНАЧЕЙСТВА ПО СУБЪЕКТАМ РОССИЙСКОЙ ФЕДЕРАЦИИ</description>
		<org>
			<name>Казначейство России</name>
			<description>Федеральное казначейство (Казначейство России) является федеральным органом исполнительной власти (федеральной службой), осуществляющим в соответствии с законодательством Российской Федерации правоприменительные функции по обеспечению исполнения федерального бюджета, кассовому обслуживанию исполнения бюджетов бюджетной системы Российской Федерации, предварительному и текущему контролю за ведением операций со средствами федерального бюджета главными распорядителями, распорядителями и получателями средств федерального бюджета.</description>
			<website>http://www.roskazna.ru/</website>
			<address>109097 г. Москва, ул. Ильинка, д. 9.</address>
		</org>
		<language>ru-RU</language>
		<location>http://www.roskazna.ru/p/fk/ter_organs.html</location>
	</source>
	<datainfo>
		<datatype is_updatable="True" />
		<created>2009-07-07T12:28:37Z</created>
		<updated>2009-07-07T12:28:37Z</updated>
		<preparedBy>
			<author>Ivan Begtin</author>
			<authorWebsite>http://ivan.begtin.name</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="roskazna_ru_TerrDepartments_table">
			<cols>
				<colspec key="num" num="1" type="integer" unique="true">
					<name>Номер</name>
					<description>Номер в списке</description>
				</colspec>
				<colspec key="name" num="2" type="string">
					<name>Наименование</name>
					<description>Наименование территориального органа</description>
				</colspec>
				<colspec key="address" num="3" type="string">
					<name>Адрс</name>
					<description>Адрес управления</description>
				</colspec>
				<colspec key="chief" num="4" type="string">
					<name>Руководитель</name>
					<description>Руководитель управления</description>
				</colspec>
				<colspec key="phone" num="5" type="string">
					<name>Телефон</name>
					<description>Один или несколько телефонов</description>
				</colspec>
				<colspec key="fax" num="6" type="string">
					<name>Факс</name>
					<description>Один или несколько номеров факса</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
		<tableref date_updated="2009-07-07T14:00:09.813807" format="CSV" hash_sha512="330a383e34e3ff116174a3e6e0219f7a8281943b7e868cbe03ff77526681799738741540320f1092c9515060081ea82748beaba3d912ead4eb2e5d9a2973b9bd" specid="roskazna_ru_TerrDepartments_table" type="full" url="http://export.opengovdata.ru/data/0.1/roskazna.ru/TerrDepartments/roskazna_ru_TerrDepartments.csv" /><tableref date_updated="2009-07-07T14:00:09.816362" format="TSV" hash_sha512="c5d8fd5fc72f350a1a33676a9b3f9ac91d44c01d08acc89805e3ddd78317fb843e0d05ca4d1ce279c7b23f9560f5163146e80d9f250e858e2e1a0e91fd19d2d8" specid="roskazna_ru_TerrDepartments_table" type="full" url="http://export.opengovdata.ru/data/0.1/roskazna.ru/TerrDepartments/roskazna_ru_TerrDepartments.tsv" /><tableref date_updated="2009-07-07T14:00:09.916048" format="openDataXML" hash_sha512="9ad22e8495f713dc02102cee954086e080d91c060851c082ff4776870f4d14cdd04da5eba718b603adfe2d39278e66991983ff347bd17ec1b64216267c6399ad" specid="roskazna_ru_TerrDepartments_table" type="full" url="http://export.opengovdata.ru/data/0.1/roskazna.ru/TerrDepartments/roskazna_ru_TerrDepartments.xml" /></current>
	</data>
</opendata>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/science_common/MKB10/opendata.xml
<?xml version='1.0' encoding='utf8'?>
<opendata ns0:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd" xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance">
	<source id="science_common_GRNI">
		<name>Международная классификация болезней 10-го пересмотра</name>
		<description>МКБ-10 — Международная классификация болезней 10-го пересмотра. На январь 2007 года является общепринятой классификацией для кодирования медицинских диагнозов, разработана Всемирной организацией здравоохранения. МКБ-10 состоит из 21-го раздела, каждый из которых содержит подразделы с кодами заболеваний и состояний.</description>
		<org>
			<name>Всемирнай организация здравоохранения (ВОЗ)</name>
			<description></description>
			<website>http://www.who.int</website>
			<address></address>
		</org>
		<language>ru-RU</language>
		<location>http://apps.who.int/classifications/apps/icd/icd10online/</location>
	</source>
	<datainfo>
		<datatype is_updatable="True" />
		<created>2010-01-29T12:28:37Z</created>
		<updated>2010-01-29T12:28:37Z</updated>
		<preparedBy>
			<author>Yuri Kudryavcev</author>
			<authorWebsite>http://www.opengovdata.ru</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="science_common_GRNTI_table">
			<cols>
				<colspec key="id" num="1" type="integer" unique="true">
					<name>Идентификатор</name>
					<description>Идентификатор (искусственный ключ)</description>
				</colspec>
				<colspec key="mkb_values" num="2" type="string">
					<name>Значение</name>
					<description>Значение записи в МКБ 10</description>
				</colspec>
				<colspec key="parent" num="3" type="integer">
					<name>Родительский код</name>
					<description>Родительский код</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
		<tableref date_updated="2010-01-29T12:00:00.0" format="CSV" hash_sha512="cf62854a61712be6966d396500cab287befcc78e2ced0a6a7c18a71a3c356bad84834d543231374167d39818555776cc5ffe9209817ae5f7bd8001a0a182a7ea" specid="science_common_MKB10_table" type="full" url="http://export.opengovdata.ru/data/0.1/science_common/MKB10/science_common_mkb10.csv" />
		</current>		
	</data>
</opendata>
