=== infoculture/opengovdataru/schema.opengovdata.ru/html/0.1/opendataindex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="opendataindex">
        <xs:annotation>
            <xs:documentation>Корневой элемент индекса открытых данных.
Общая структура opendataindex аналогична структуре файлов sitemap index
</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="opendata">
                    <xs:annotation>
                        <xs:documentation>Открытые данные - включает ссылку на массив данных и дату его изменения</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="loc" type="xs:string">
                                <xs:annotation>
                                    <xs:documentation>Абсолютная ссылка на описание массива данных</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="lastmod" type="xs:dateTime">
                                <xs:annotation>
                                    <xs:documentation>Дата последнего изменения</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== infoculture/opengovdataru/export.opengovdata.ru/html/opendataindex.xml
<?xml version="1.0" encoding="UTF-8"?>
<opendataindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendataindex.xsd">
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/gibdd.ru/AutoCodes/opendata.xml</loc>
        <lastmod>2009-04-22T16:28:37Z</lastmod>
    </opendata>
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/kremlin.ru/KadryReserv/opendata.xml</loc>
        <lastmod>2009-04-22T16:28:37Z</lastmod>
    </opendata>    
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/roskazna.ru/TerrDepartments/opendata.xml</loc>
        <lastmod>2009-07-07T12:00:11Z</lastmod>
    </opendata>        
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/science_common/GRNTI/opendata.xml</loc>
        <lastmod>2009-08-31T10:00:11Z</lastmod>
    </opendata>        
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/science_common/MKB10/opendata.xml</loc>
        <lastmod>2009-08-31T10:00:11Z</lastmod>
    </opendata>        
    <opendata>
        <loc>http://export.opengovdata.ru/data/0.1/zakupki.gov.ru/Nomenklatura/opendata.xml</loc>
        <lastmod>2009-08-31T10:00:11Z</lastmod>
    </opendata>        
</opendataindex>
