=== infoculture/opengovdataru/schema.opengovdata.ru/html/0.1/opendata.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio - FREE Community Edition 7.1.0.1135 (http://www.liquid-technologies.com)-->
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified"
  elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="opendata">
    <xs:annotation>
      <xs:documentation>Корневой тэг спецификации открытых данных</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" name="source">
          <xs:annotation>
            <xs:documentation>Описание источника данных</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="1" name="name" type="xs:string">
                <xs:annotation>
                  <xs:documentation xml:lang="ru">Наименование источника информации</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="description" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Подробное описание источника данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="org">
                <xs:annotation>
                  <xs:documentation>Информация об организации ведующей данный массив данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="1" name="name" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Наименование ответственной организации</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="description" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Описание организации
</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="website" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Веб-сайт организации ведущей данный источник информации</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="1" name="address" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Юридический адрес местонахождения организации ведущей данный источник данных</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="language" type="xs:string">
                <xs:annotation>
                  <xs:documentation>Язык на котором представлена информация в источнике данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" name="location" type="xs:string">
                <xs:annotation>
                  <xs:documentation>веб-ссылка на источник данных если он есть. Может ссылаться на http и ftp ресурсы</xs:documentation>
                </xs:annotation>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required">
              <xs:annotation>
                <xs:documentation xml:lang="ru">Уникальный идентификатор источника информации</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="datainfo">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="datatype">
                <xs:annotation>
                  <xs:documentation>Информация о типе массива данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="is_updatable" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Флаг отмечаемый в True если источник данных не является статическим и пополняется новой информацией и в False если он является статическим</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="created" type="xs:dateTime">
                <xs:annotation>
                  <xs:documentation>Дата создания массива данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="1" maxOccurs="1" name="updated" type="xs:dateTime">
                <xs:annotation>
                  <xs:documentation>Дата последнего обновления источника данных</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element minOccurs="0" maxOccurs="1" name="preparedBy">
                <xs:annotation>
                  <xs:documentation>Информация о человеке подготовившем материалы для данного источника информации</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="1" name="author" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>ФИО автора </xs:documentation>
                      </xs:annotation>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="1" name="authorWebsite" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Сайт автора (если есть)</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="specs">
          <xs:annotation>
            <xs:documentation>Спецификации и описание структуры данных из источника</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="specref">
                <xs:annotation>
                  <xs:documentation>Сслылка на описание спецификации во внешнем файле</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Идентификатор спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="url" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Веб-ссылка на документ спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                  <xs:attribute name="isSpecial" type="xs:boolean" use="required">
                    <xs:annotation>
                      <xs:documentation>Флаг того представлена ли спецификация в специальном формате. Например, в виде простого описания</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="tablespec">
                <xs:annotation>
                  <xs:documentation>Спецификация табличных данных</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="cols">
                      <xs:annotation>
                        <xs:documentation>Перечень спецификаций столбцов</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="colspec">
                            <xs:annotation>
                              <xs:documentation>Спецификация столбца данных</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="name" type="xs:string">
                                  <xs:annotation>
                                    <xs:documentation>Название столбца</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                                <xs:element minOccurs="0" name="description" type="xs:string">
                                  <xs:annotation>
                                    <xs:documentation>Описание столбца</xs:documentation>
                                  </xs:annotation>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="num" type="xs:unsignedByte" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Номер столбца от начала ряда в таблице</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="key" type="xs:string" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Уникальный ключ, идентификатор данного столбца</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="unique" type="xs:boolean" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Если установлен в True, то данные в столбце являеются уникальными в рамках всей таблицы</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                              <xs:attribute name="type" type="xs:string" use="optional">
                                <xs:annotation>
                                  <xs:documentation>Тип данных в столбце. Может принимать значения:
1. string - строка
2. integer - число
3. url - ссылка на внешний ресурс
4. date - дата в формате ISO:  YYYY-MM-DD
5. datetime - дата и время в формате ISO: YYYY-MM-DD HH:MM:SS</xs:documentation>
                                </xs:annotation>
                              </xs:attribute>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:string" use="required">
                    <xs:annotation>
                      <xs:documentation>Идентификатор спецификации</xs:documentation>
                    </xs:annotation>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="data">
          <xs:annotation>
            <xs:documentation>Открытые данные</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="current">
                <xs:annotation>
                  <xs:documentation>Текущие данные</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="table">
                      <xs:annotation>
                        <xs:documentation>Таблица с  данными</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="row">
                            <xs:annotation>
                              <xs:documentation>Ряд - запись в таблице</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" maxOccurs="unbounded" name="col">
                                  <xs:annotation>
                                    <xs:documentation>Столбец в записи таблицы</xs:documentation>
                                  </xs:annotation>
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="num" type="xs:unsignedByte"
                                          use="required">
                                          <xs:annotation>
                                            <xs:documentation>Номер столбца в записи - уникален в пределах одной записи</xs:documentation>
                                          </xs:annotation>
                                        </xs:attribute>
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="specid" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Идентификатор спецификации</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="type" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Тип таблицы</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="date_updated" type="xs:dateTime" use="required">
                          <xs:annotation>
                            <xs:documentation>Дата последнего обновления</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="tableref">
                      <xs:annotation>
                        <xs:documentation>Ссылка на внешний файл таблицы с данными</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:attribute name="type" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Тип таблицы - может принимать одно из значений:
1. full - таблица со всеми данными
2. initial - начальные данные на которые далее накладываются все обновления. Должен обладать updateid = 0
2. update - обновления к начальным данным которые обладают updateid инкрементально возрастающим от обновления к обновлению</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="specid" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Идентификатор спецификации данных</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="format" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Формат данных в таблице. Может быть одним из значений:
1. CSV
2. TSV
3. DBF
4. XML</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="url" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Ссылка на внешний файл с данными в указанном формате</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="hash_sha512" type="xs:string" use="required">
                          <xs:annotation>
                            <xs:documentation>Хэш внешнего файла рассчитанный по алгоритму SHA-512</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="date_updated" type="xs:dateTime" use="required">
                          <xs:annotation>
                            <xs:documentation>Дата последнего обновления</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                        <xs:attribute name="updateid" type="xs:unsignedLong" use="optional">
                          <xs:annotation>
                            <xs:documentation>Идентификатор обновления если тип таблицы update, то это инкрементальное число начинающееся от 1.
Если тип таблицы initial, то updateid всегда равен 0
Для таблиц типа full - не используется</xs:documentation>
                          </xs:annotation>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/kremlin.ru/KadryReserv/opendata.xml
<?xml version="1.0" encoding="utf-8"?>
<opendata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd">
	<source id="kremlin_ru_KadryReserv">
		<name>Кадровый резерв при президенте России</name>
		<description>Кадровый резерв при президенте России</description>
		<org>
			<name>Управление пресс-службы и информации Президента</name>
			<description>Управление пресс-службы и информации Президента Российской Федерации</description>
			<website>http://www.kremlin.ru</website>
			<address>
			</address>
		</org>
		<language>ru-RU</language>
		<location>http://www.kremlin.ru/images/rezerv.doc</location>
	</source>
	<datainfo>
		<datatype is_updatable="False" />
		<created>2009-04-22T16:28:37Z</created>
		<updated>2009-04-22T16:28:37Z</updated>
		<preparedBy>
			<author>Ivan Begtin</author>
			<authorWebsite>http://ivan.begtin.name</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="kremlin_ru_KadryReserv_table">
			<cols>
				<colspec num="1" key="code" unique="true" type="integer">
					<name>Номер</name>
					<description>Номер персоны в списке</description>
				</colspec>
				<colspec num="2" key="fullname" type="string">
					<name>ФИО</name>
					<description>Фамилия, имя, отчество</description>
				</colspec>
				<colspec num="3" key="surname" type="string">
					<name>Фамилия</name>
					<description>Фамилия персоны</description>
				</colspec>
				<colspec num="4" key="name" type="string">
					<name>Имя</name>
					<description>Имя персоны</description>
				</colspec>
				<colspec num="5" key="middlename" type="string">
					<name>Отчество</name>
					<description>Отчество персоны</description>
				</colspec>
				<colspec num="6" key="gender" type="integer">
					<name>Пол</name>
					<description>0 - мужской пол, 1 - женский</description>
				</colspec>
				<colspec num="7" key="bornYear" type="integer">
					<name>Год рождения</name>
					<description>Год рождения от рождества Христова</description>
				</colspec>
				<colspec num="8" key="organization" type="string">
					<name>Организация</name>
					<description>Наименование организации</description>
				</colspec>
				<colspec num="9" key="position" type="string">
					<name>Должность</name>
					<description>Должность персоны в организации</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
			<tableref type="full" specid="ru_KremlinKadryReserv_table" format="openDataXML" url="http://export.opengovdata.ru/data/0.1/kremlin.ru/KadryReserv/ru_KremlinKadry.xml" hash_sha512="fc2a4050b64325c27003fa81a18a13d21d3c30b2dcdf949ec32a9ff6a53e9f0b87bf6d331f7cb9a88d55c7fc68db4a4fd445a5452bcc24f963f1da73cb8bca16" date_updated="2009-04-22T16:28:37Z" />
			<tableref type="full" specid="ru_KremlinKadryReserv_table" format="CSV" url="http://export.opengovdata.ru/data/0.1/kremlin.ru/KadryReserv/ru_KremlinKadry.csv" hash_sha512="1da3706e3839cd3f5e27e0d36280ac10fa4a397e9a2d209229fd59b0487c94d1fe33f41f26c8bfe15760b38f96d3c6969c76920063882e37e65b1073cfa8f7e1" date_updated="2009-04-22T16:28:37Z" />
			<tableref type="full" specid="ru_KremlinKadryReserv_table" format="TSV" url="http://export.opengovdata.ru/data/0.1/kremlin.ru/KadryReserv/ru_KremlinKadry.tsv" hash_sha512="37f8be0ab330cc4fc8ab79e80f9125dbba3a65f9c1cf15a3ab453ad2e72efbe1ff585d0a2385c93997bbdd20de258fe57c3963a5e182a574378efabc9b89b2be" date_updated="2009-04-22T16:28:37Z" />
		</current>
	</data>
</opendata>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/science_common/GRNTI/opendata.xml
<?xml version='1.0' encoding='utf8'?>
<opendata ns0:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd" xmlns:ns0="http://www.w3.org/2001/XMLSchema-instance">
	<source id="science_common_GRNI">
		<name>Государственный рубрикатор научно-технической информации (ГРНТИ)</name>
		<description>Государственный рубрикатор научно-технической информации (прежнее наименование - Рубрикатор ГАСНТИ) представляет собой универсальную иерархическую классификацию областей знания, принятую для систематизации всего потока научно-технической информации. На основе Рубрикатора построена система локальных (отраслевых, тематических, проблемных) рубрикаторов в органах научно-технической информации.</description>
		<org>
			<name>Всероссийский институт научной и технической информации (ВИНИТИ)</name>
			<description>Институт проводит фундаментальные и прикладные исследования в области информатики (научно-информационной деятельности)</description>
			<website>http://www2.viniti.ru</website>
			<address>Россия, 125190, Москва, А-190, ул. Усиевича, д. 20</address>
		</org>
		<language>ru-RU</language>
		<location>http://www2.viniti.ru</location>
	</source>
	<datainfo>
		<datatype is_updatable="True" />
		<created>2009-07-07T12:28:37Z</created>
		<updated>2009-07-07T12:28:37Z</updated>
		<preparedBy>
			<author>Ivan Begtin</author>
			<authorWebsite>http://ivan.begtin.name</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="science_common_GRNTI_table">
			<cols>
				<colspec key="code" num="1" type="integer" unique="true">
					<name>Код</name>
					<description>Код справочника</description>
				</colspec>
				<colspec key="name" num="2" type="string">
					<name>Наименование</name>
					<description>Наименование записи</description>
				</colspec>
				<colspec key="level" num="3" type="integer">
					<name>Уровень</name>
					<description>Уровень кода в иерархии от 0 до 2.</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
		<tableref date_updated="2009-08-31T03:09:10.540728" format="CSV" hash_sha512="dc90209ab9b16375f174ad845415dfb4289c7db64791415fa50a536688ffc3294db0c5c842012ca2bb5f744033efa4e4de812a021c65cf355f966942fd6cedf2" specid="science_common_GRNTI_table" type="full" url="http://export.opengovdata.ru/data/0.1/science_common/GRNTI/science_common_grnti.csv" />
		<tableref date_updated="2009-08-31T03:09:10.834102" format="TSV" hash_sha512="472ced5c0151f07e643e4b7ac5345f4313369e96535d69091416667dacc38aa26a845a7f877c93e5075c90fe78961e0f45331cb18ab35e58f90ecd1e9177046c" specid="science_common_GRNTI_table" type="full" url="http://export.opengovdata.ru/data/0.1/science_common/GRNTI/science_common_grnti.tsv" />
		<tableref date_updated="2009-08-31T03:09:32.305397" format="openDataXML" hash_sha512="d12db80fd9247f5cd30e59caf8fade0ec3d63b45b35ea69f677ad1fb483df55da36b5eb2e17ee5414cabc324d9bf3a8513f9cb1d2f072f29f1e4fcc66ae4ff09" specid="science_common_GRNTI_table" type="full" url="http://export.opengovdata.ru/data/0.1/science_common/GRNTI/science_common_grnti.xml" /></current>
	</data>
</opendata>

=== infoculture/opengovdataru/export.opengovdata.ru/html/data/0.1/gibdd.ru/AutoCodes/opendata.xml
<?xml version="1.0" encoding="utf-8"?>
<opendata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://schema.opengovdata.ru/0.1/opendata.xsd">
	<source id="gibdd_ru_AutoCodes">
		<name>Перечень цифровых кодов регионов Российской Федерации применяемых на государственных регистрационных знаках транспортных средств и другой специальной технике</name>
		<description>Перечень цифровых кодов регионов Российской Федерации применяемых на государственных регистрационных знаках транспортных средств и другой специальной технике (в формате приказа МВД России от 28 марта 2002 г. N 282 О ГОСУДАРСТВЕННЫХ РЕГИСТРАЦИОННЫХ ЗНАКАХ ТРАНСПОРТНЫХ СРЕДСТВ</description>
		<org>
			<name>Госавтоинспекция МВД России</name>
			<description>Департамент обеспечения безопасности дорожного движения МВД России</description>
			<website>http://www.gibdd.ru</website>
			<address></address>
		</org>
		<language>ru-RU</language>
	</source>
	<datainfo>
		<datatype is_updatable="False" />
		<created>2009-04-22T16:28:37Z</created>
		<updated>2009-04-22T16:28:37Z</updated>
		<preparedBy>
			<author>Ivan Begtin</author>
			<authorWebsite>http://ivan.begtin.name</authorWebsite>
		</preparedBy>
	</datainfo>
	<specs>
		<tablespec id="gibdd_ru_AutoCodes_table">
			<cols>
				<colspec num="1" key="code" unique="true" type="string">
					<name>Код ГИБДД</name>
					<description>Код транспортного средства</description>
				</colspec>
				<colspec num="2" key="regionName" type="string">
					<name>Название региона</name>
					<description>Название региона Российской федерации или иного способа применения номера</description>
				</colspec>
				<colspec num="3" key="regionKLADRCode" type="string">
					<name>Код КЛАДР</name>
					<description>Код КЛАДР связанного с кодом региона</description>
				</colspec>
				<colspec num="4" key="isActual" type="boolean">
					<name>Актуальность кода</name>
					<description>Если 1 код действующий, если 0 - недействующий</description>
				</colspec>
				<colspec num="5" key="isSpecial" type="boolean">
					<name>Особенный код</name>
					<description>Если 0 - код привязан к региону, если 1 - код не имеет региональной привязки</description>
				</colspec>
			</cols>
		</tablespec>
	</specs>
	<data>
		<current>
			<tableref type="full" specid="gibdd_ru_AutoCodes_table" date_updated="2009-04-22T16:28:37" format="openDataXML" url="http://export.opengovdata.ru/data/0.1/gibdd.ru/AutoCodes/gibdd_ru_AutoCodes.xml" hash_sha512="48a87401946ca7ee7738672cc6d0629b71916a7824ffaa9257a775460031835d26f3498619cfa36add0f2ba0d8a7d946d65b3d9b307859a4577f8c2e66dac33e" />
			<tableref type="full" specid="gibdd_ru_AutoCodes_table" date_updated="2009-04-22T16:28:37" format="CSV" url="http://export.opengovdata.ru/data/0.1/gibdd.ru/AutoCodes/gibdd_ru_AutoCodes.csv" hash_sha512="4eb606c591c1ccc8d3ce5f253b2b1ab0476e2ba7568ca8565f3aba20e265d7f16547d15ce553e75106a9159466cb551b98621ce97458ac24a8fadcd0a563d6f8" />
			<tableref type="full" specid="gibdd_ru_AutoCodes_table" date_updated="2009-04-22T16:28:37" format="TSV" url="http://export.opengovdata.ru/data/0.1/gibdd.ru/AutoCodes/gibdd_ru_AutoCodes.tsv" hash_sha512="4fd1c0364fa3b75c87053cd15ce2747a547d8755213515aea2406885cbe32f34ad5f46f84d19b0ab33c51e06f36cacf02e5457c24c36c7b65c207d5a58e6fed2" />
		</current>
	</data>
</opendata>
